import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const projectRoot = resolve(import.meta.dirname, "..");
const publicHead = readFileSync(resolve(projectRoot, "client/index.html"), "utf8");
const homePage = readFileSync(resolve(projectRoot, "client/src/pages/Home.tsx"), "utf8");
const tributaryPage = readFileSync(resolve(projectRoot, "client/consultoria-tributaria/index.html"), "utf8");
const fiscalPage = readFileSync(resolve(projectRoot, "client/consultoria-fiscal/index.html"), "utf8");
const blogPage = readFileSync(resolve(projectRoot, "client/blog/index.html"), "utf8");
const successCasesPage = readFileSync(resolve(projectRoot, "client/casos-de-sucesso/index.html"), "utf8");
const presentationPage = readFileSync(resolve(projectRoot, "client/apresentacao/index.html"), "utf8");
const aboutPage = readFileSync(resolve(projectRoot, "client/sobre-a-cenvara/index.html"), "utf8");
const aboutComponent = readFileSync(resolve(projectRoot, "client/src/pages/About.tsx"), "utf8");
const successCasesComponent = readFileSync(resolve(projectRoot, "client/src/pages/SuccessCases.tsx"), "utf8");
const presentationComponent = readFileSync(resolve(projectRoot, "client/src/pages/Presentation.tsx"), "utf8");
const blogComponent = readFileSync(resolve(projectRoot, "client/src/pages/Blog.tsx"), "utf8");
const sitemap = readFileSync(resolve(projectRoot, "client/public/sitemap.xml"), "utf8");
const form = readFileSync(resolve(projectRoot, "client/src/components/LeadQualificationForm.tsx"), "utf8");
const analytics = readFileSync(resolve(projectRoot, "client/src/lib/analytics.ts"), "utf8");

describe("metadados institucionais da Cenvara", () => {
  it("declara São Paulo, SP no SEO e nos dados estruturados", () => {
    expect(publicHead).toContain("consultoria tributária São Paulo");
    expect(publicHead).toContain('"addressLocality":"São Paulo"');
    expect(publicHead).toContain('"addressRegion":"SP"');
    expect(publicHead).toContain("Cenvara Fiscal & Estratégia em São Paulo, SP");
    expect(tributaryPage).toContain("Consultoria Tributária em São Paulo, SP");
    expect(fiscalPage).toContain("Consultoria Fiscal em São Paulo, SP");
    expect(tributaryPage).toContain('"@type":"Service"');
    expect(tributaryPage).toContain('"serviceType":"Consultoria tributária"');
    expect(fiscalPage).toContain('"@type":"Service"');
    expect(fiscalPage).toContain('"serviceType":"Consultoria fiscal"');
  });

  it("publica o Caderno Cenvara com descoberta técnica e editorial", () => {
    expect(blogPage).toContain("Artigos fiscais e tecnológicos");
    expect(blogPage).toContain('rel="canonical"');
    expect(blogComponent).toContain("Caderno Cenvara");
    expect(blogComponent).toContain("Agosto de 2026");
    expect(blogComponent).toContain('"@type": "BlogPosting"');
    expect(blogComponent).toContain("relatedHref");
    expect(blogPage).toContain('"@type":"CollectionPage"');
    expect(sitemap).toContain("https://cenvara-consultoria.web.app/blog");
    expect(sitemap).toContain("https://cenvara-consultoria.web.app/casos-de-sucesso");
    expect(sitemap).toContain("https://cenvara-consultoria.web.app/apresentacao");
    expect(sitemap).toContain("https://cenvara-consultoria.web.app/sobre-a-cenvara");
    expect(aboutPage).toContain("Sobre a Cenvara");
    expect(aboutPage).toContain('property="og:image"');
    expect(aboutPage).toContain('"@type":"AboutPage"');
    expect(aboutComponent).toContain("Rusevel Barros");
    expect(aboutComponent).toContain("Jessica Carvalho");
    expect(successCasesPage).toContain("Casos de Sucesso");
    expect(presentationPage).toContain("Apresentação Comercial");
    expect(successCasesComponent).toContain("relatos autorizados");
    expect(successCasesComponent).toContain("Não exibimos métricas numéricas");
    expect(presentationComponent).toContain("deck_download");
    expect(presentationComponent).toContain("ArrowRight");
    expect(presentationComponent).toContain("documento comercial");
    expect(presentationComponent).toContain("Tela {current.number}");
    expect(presentationComponent).toContain("BackToTop");
    expect(successCasesComponent).toContain("BackToTop");
    expect(successCasesPage).toContain('property="og:image"');
    expect(presentationPage).toContain('property="og:image"');
    expect(presentationComponent).toContain('role="progressbar"');
    expect(presentationComponent).toContain("/deck-comercial-cenvara.pdf");
    expect(successCasesComponent).toContain("LeadQualificationForm");
    expect(successCasesComponent).toContain("próximo passo");
    expect(successCasesPage).toContain('property="og:site_name"');
    expect(successCasesPage).toContain('name="twitter:description"');
    expect(presentationPage).toContain('property="og:site_name"');
    expect(presentationPage).toContain('name="twitter:description"');
  });

  it("mantém contato global e confirmação acessível do formulário", () => {
    const app = readFileSync(resolve(projectRoot, "client/src/App.tsx"), "utf8");
    const floatingWhatsApp = readFileSync(resolve(projectRoot, "client/src/components/FloatingWhatsApp.tsx"), "utf8");
    const footer = readFileSync(resolve(projectRoot, "client/src/components/SiteFooter.tsx"), "utf8");
    expect(app).toContain("<FloatingWhatsApp />");
    expect(floatingWhatsApp).toContain("whatsapp_float_click");
    expect(footer).toContain("61593543042320");
    expect(footer).toContain('facebook_click');
    expect(footer).toContain("cenvara-consult-33445a431");
    expect(footer).toContain('linkedin_click');
    expect(footer).toContain("pin.it/2KEwvnz2X");
    expect(footer).toContain('pinterest_click');
    expect(footer).toContain("instagram.com/cenvaraconsult");
    expect(footer).toContain('instagram_click');
    expect(footer).toContain("tiktok.com/@cenvaraconsult");
    expect(footer).toContain('tiktok_click');
    expect(footer).toContain("youtube.com/channel/UCYKzfZw0S-WiJ1WdHTgo2ww");
    expect(footer).toContain('youtube_click');
    expect(homePage).toContain('deck_download');
    expect(footer).toContain('social-link');
    expect(footer).toContain('data-tooltip');
    expect(footer).toContain('Canais sociais da Cenvara');
    expect(analytics).toContain('cenvara-analytics-consent');
    expect(analytics).toContain('!== "granted"');
    expect(footer).toContain('rel="noopener noreferrer"');
    expect(form).toContain('role="status"');
    expect(form).toContain("successRef");
    expect(form).toContain("Solicitação registrada.");
  });

  it("mantém Rusevel Barros como CEO & CTO na apresentação institucional", () => {
    expect(publicHead).toContain('"name":"Rusevel Barros"');
    expect(publicHead).toContain('"jobTitle":"CEO & CTO"');
    expect(homePage).toContain("Rusevel Barros");
    expect(homePage).toContain('role="CEO & CTO"');
    expect(publicHead).toContain("Consultor de tecnologia e analista de negócios");
    expect(homePage).toContain("automação de fluxos");
    expect(publicHead).toContain('"name":"Jessica Carvalho"');
    expect(publicHead).toContain('"jobTitle":"Sócia e Cofundadora | GFS — Gestora Fiscal Sênior"');
    expect(homePage).toContain("Jessica Carvalho");
    expect(homePage).toContain("GFS — Gestora Fiscal Sênior");
  });
});
